Port: 0

Settings:
  AdminPanel: "enable"

Database:
  Host: "localhost"
  Port: 5432
  User: "lx"
  Password: "123456"
  DBName: "lxgoauthtest"
  SSLMode: "disable"

Templates:
  - templates

Components:
  SessionStorage:
    CookieName: lxgoauthsessionid
    MaxLifeTime: 36000
